spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: bancoespacial
    password: bancoespacial
    initialization-mode: always
    url: jdbc:oracle:thin:@localhost:1521:ee
    sqlScriptEncoding: UTF-8
  jpa:
    properties:
      hibernate:
        spatial:
          connection_finder: br.com.postgis.postgres.CustomConnectionFinderForSpatialSupport
          dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
