spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    initialization-mode: always
    url: jdbc:oracle:thin:@localhost:1521:ee
    sqlScriptEncoding: UTF-8
    password: oracle
  jpa:
    properties:
      hibernate:
        spatial:
          connection_finder: br.com.postgis.postgres.CustomConnectionFinderForSpatialSupport
          dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
        dialect: org.hibernate.dialect.Oracle12cDialect
      GEOLATTE_USE_SDO_POINT_TYPE: 'true'
    hibernate:
      ddl-auto: create
