spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ee
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    sqlScriptEncoding: UTF-8
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        spatial:
          ogc_strict: true
          enabled: true
          dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
          connection_finder: br.com.postgis.postgres.CustomConnectionFinderForSpatialSupport
        dialect: org.hibernate.dialect.Oracle12cDialect








